# Generated by Django 6.0.3 on 2026-03-17 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('academic', 'Egitim-ogretim destegi'), ('accessible_material', 'Erisilebilir materyal destegi'), ('joint_study', 'Birlikte ders calisma'), ('visual_description', 'Gorsel betimleme destegi'), ('wayfinding', 'Yon bulma destegi'), ('daily_life', 'Gunluk yasam destegi')], max_length=32)),
                ('course_name', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('urgency', models.CharField(choices=[('low', 'Dusuk'), ('medium', 'Orta'), ('high', 'Yuksek')], default='medium', max_length=16)),
                ('preferred_timing', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('open', 'Acik'), ('matched', 'Eslesti'), ('in_progress', 'Suruyor'), ('completed', 'Tamamlandi'), ('cancelled', 'Iptal edildi')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_requests', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_support_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
