# Generated by Django 6.0.3 on 2026-03-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_requestmaterial_requestmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportrequest',
            name='category',
            field=models.CharField(choices=[('academic', 'Eğitim-öğretim desteği'), ('accessible_material', 'Erişilebilir materyal desteği'), ('joint_study', 'Birlikte ders çalışma'), ('visual_description', 'Görsel betimleme desteği'), ('wayfinding', 'Yön bulma desteği'), ('daily_life', 'Günlük yaşam desteği')], max_length=32),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='status',
            field=models.CharField(choices=[('open', 'Açık'), ('matched', 'Eşleşti'), ('in_progress', 'Sürüyor'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal edildi')], default='open', max_length=16),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='urgency',
            field=models.CharField(choices=[('low', 'Düşük'), ('medium', 'Orta'), ('high', 'Yüksek')], default='medium', max_length=16),
        ),
    ]
