# Generated by Django 6.0.3 on 2026-03-18 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_alter_supportrequest_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrequest',
            name='priority',
            field=models.CharField(choices=[('normal', 'Normal'), ('high', 'Yüksek öncelik'), ('critical', 'Kritik öncelik')], default='normal', max_length=16),
        ),
        migrations.CreateModel(
            name='SupportRequestActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('request_created', 'Talep oluşturuldu'), ('status_updated', 'Durum güncellendi'), ('priority_updated', 'Öncelik güncellendi'), ('volunteer_assigned', 'Gönüllü atandı'), ('intervention_note', 'Müdahale notu eklendi'), ('message_posted', 'Mesaj gönderildi'), ('material_uploaded', 'Materyal yüklendi')], max_length=32)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_activity_logs', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='support.supportrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportRequestInterventionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_intervention_notes', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervention_notes', to='support.supportrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
