# Generated by Django 6.0.3 on 2026-03-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_supportrequest_priority_supportrequestactivitylog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrequest',
            name='duration_unit',
            field=models.CharField(blank=True, choices=[('day', 'Gün'), ('week', 'Hafta'), ('month', 'Ay')], max_length=16),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='duration_value',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='requested_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
