# Generated by Codex on 2026-03-19

from django.db import migrations, models

import support.models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0005_supportrequest_duration_unit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestmaterial",
            name="file",
            field=models.FileField(
                max_length=255,
                upload_to=support.models.request_material_upload_to,
            ),
        ),
    ]
