# Generated by Django 6.0.3 on 2026-03-25 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0007_supportrequestinterventionnote_priority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportrequest',
            name='category',
            field=models.CharField(choices=[('accessible_material', 'Erişilebilir materyal hazırlama'), ('audio_narration', 'Seslendirme'), ('academic', 'Akademik destek'), ('joint_study', 'Birlikte ders çalışma'), ('visual_description', 'Görsel betimleme'), ('resource_access', 'Kaynak erişimi'), ('exam_preparation', 'Sınav hazırlık'), ('wayfinding', 'Bağımsız hareket, yön bulma ve rehberlik'), ('daily_life', 'Günlük yaşam'), ('social_activity', 'Sosyal etkinlik')], max_length=32),
        ),
        migrations.AddIndex(
            model_name='supportrequest',
            index=models.Index(fields=['status'], name='supportreq_status_idx'),
        ),
        migrations.AddIndex(
            model_name='supportrequest',
            index=models.Index(fields=['priority'], name='supportreq_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='supportrequest',
            index=models.Index(fields=['category'], name='supportreq_category_idx'),
        ),
        migrations.AddIndex(
            model_name='supportrequest',
            index=models.Index(fields=['created_by', '-created_at'], name='supportreq_createdby_date_idx'),
        ),
        migrations.AddIndex(
            model_name='supportrequest',
            index=models.Index(fields=['assigned_volunteer', 'status'], name='supportreq_vol_status_idx'),
        ),
        migrations.AddIndex(
            model_name='supportrequest',
            index=models.Index(fields=['requested_completion_date'], name='supportreq_deadline_idx'),
        ),
    ]
