# Generated by Django 6.0.3 on 2026-03-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('visually_impaired_student', 'Gorme engelli ogrenci'), ('volunteer_student', 'Gonullu ogrenci'), ('academic_advisor', 'Akademik danisman'), ('coordinator', 'Koordinator')], max_length=32),
        ),
    ]
