# Generated by Django 6.0.3 on 2026-03-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('visually_impaired_student', 'Görme engelli öğrenci'), ('volunteer_student', 'Gönüllü öğrenci'), ('academic_advisor', 'Akademik danışman'), ('coordinator', 'Koordinatör')], max_length=32),
        ),
    ]
